// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO_xWqhrwsRJP291eE8Xbuay795X2-emk',
    appId: '1:207989987902:web:22775b1eafc14c8b5c4f6f',
    messagingSenderId: '207989987902',
    projectId: 'gadypadieclinic-c9d35',
    authDomain: 'gadypadieclinic-c9d35.firebaseapp.com',
    storageBucket: 'gadypadieclinic-c9d35.firebasestorage.app',
    measurementId: 'G-S9EMT15NBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJW-AIF0po2MlpJ7YEGgRpBcXKduXLXek',
    appId: '1:207989987902:android:fea93800a1a52fc25c4f6f',
    messagingSenderId: '207989987902',
    projectId: 'gadypadieclinic-c9d35',
    storageBucket: 'gadypadieclinic-c9d35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBluNMHpib4dDfieUsG7C9SdBP2XaTan7g',
    appId: '1:207989987902:ios:7bfc569582f5a0a45c4f6f',
    messagingSenderId: '207989987902',
    projectId: 'gadypadieclinic-c9d35',
    storageBucket: 'gadypadieclinic-c9d35.firebasestorage.app',
    iosBundleId: 'com.example.gadypadieclinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBluNMHpib4dDfieUsG7C9SdBP2XaTan7g',
    appId: '1:207989987902:ios:7bfc569582f5a0a45c4f6f',
    messagingSenderId: '207989987902',
    projectId: 'gadypadieclinic-c9d35',
    storageBucket: 'gadypadieclinic-c9d35.firebasestorage.app',
    iosBundleId: 'com.example.gadypadieclinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO_xWqhrwsRJP291eE8Xbuay795X2-emk',
    appId: '1:207989987902:web:72521b7f6febc48e5c4f6f',
    messagingSenderId: '207989987902',
    projectId: 'gadypadieclinic-c9d35',
    authDomain: 'gadypadieclinic-c9d35.firebaseapp.com',
    storageBucket: 'gadypadieclinic-c9d35.firebasestorage.app',
    measurementId: 'G-G9NZFNBQ7M',
  );
}
